apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: thanos-query-frontend
spec:
  selector:
    matchLabels:
      app: thanos-query-frontend
      monitored-by-prometheus: "true"
  namespaceSelector:
    any: true
  endpoints:
    - interval: 15s
      targetPort: web
      path: /metrics