apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: thanos-query
spec:
  selector:
    matchLabels:
      app: thanos-query
      monitored-by-prometheus: "true"
  namespaceSelector:
    any: true
  endpoints:
    - interval: 15s
      targetPort: http
      path: /metrics